### ISSUE TITLE
Expression.Error: The type of the value does not match the type of the column.

### ISSUE THREAD

**Issue by iRajatsolanki1** [ramajayam-CA/Tally-Connector#2]
![Screenshot (167)](https://github.com/ramajayam-CA/Tally-Connector/assets/157574960/f0cdf6b1-d2f7-49dc-b449-acb0f54fb060)
All records are showing error 
I am Using Office 365 64 bit and tally 3.0

**Comment by ramajayam-CA** [comment]
Please use Microsoft query import option ...

It will certainly work
