### ISSUE TITLE
Error while connecting excel using microsoft query

### ISSUE THREAD

**Issue by ravirajbrao189** [ramajayam-CA/Tally-Connector#4]
The database does not show the tally ODBC option.
[Error.xlsx](https://github.com/ramajayam-CA/Tally-Connector/files/14614051/Error.xlsx)

**Comment by ramajayam-CA** [comment]
Run Tally in Administrator Mode

**Comment by ramajayam-CA** [comment]
Run Tally in Administrator Mode
